import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar2 from "@/components/Sidebar2";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} relative flex flex-row`}>
        <div className="flex flex-1">
          <Sidebar2 />
        </div>
        <div className="mb-48 ml-4 mr-4 mt-4 flex-grow"> {children} </div>
      </body>
    </html>
  );
}
